# Generated by Django 4.1.5 on 2023-01-23 03:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AboutFeatureCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name="AboutStaff",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("designation", models.CharField(max_length=100)),
                (
                    "image",
                    models.ImageField(
                        upload_to="post",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["png", "jpg"]
                            )
                        ],
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AboutUs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=225)),
                ("body", models.TextField()),
                (
                    "image",
                    models.ImageField(
                        upload_to="post",
                        validators=[
                            django.core.validators.FileExtensionValidator(
                                ["png", "jpg"]
                            )
                        ],
                    ),
                ),
            ],
        ),
    ]
