# Generated by Django 4.1.5 on 2023-01-23 04:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aboutstaff",
            name="image",
            field=models.ImageField(
                upload_to="post",
                validators=[
                    django.core.validators.FileExtensionValidator(
                        ["png", "jpg", "jpeg"]
                    )
                ],
            ),
        ),
        migrations.CreateModel(
            name="Choose",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                (
                    "name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="home.aboutfeaturecategory",
                    ),
                ),
            ],
        ),
    ]
