# Generated by Django 4.1.5 on 2023-01-23 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0003_service"),
    ]

    operations = [
        migrations.CreateModel(
            name="WorkProcess",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=225)),
                ("body", models.TextField()),
            ],
        ),
    ]
